name: .NET Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
          
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        # The wildcard filter that identifies projects to version
        projectFilter: "**/HtmlCompiler.csproj"
        # Maps to the Version element
        version: 1.0.${{ github.run_number }}
        # Maps to the AssemblyVersion element
        assemblyVersion: 1.0.${{ github.run_number }}
        # Maps to the FileVersion element
        fileVersion: 1.0.${{ github.run_number }}
        # Maps to the InformationalVersion element
        informationalVersion: 1.0.${{ github.run_number }}
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
        
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        dotnet tool update -g dotnet-sonarscanner
        dotnet tool update -g dotnet-reportgenerator-globaltool
      
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: pwsh
      run: |
        dotnet-sonarscanner begin /k:"lk-code_html-compiler-tool" /o:"lk-code-github" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build --configuration Release --no-restore -p:PackageVersion=1.0.${{ github.run_number }}
        dotnet test --no-build --collect:"XPlat Code Coverage"
        reportgenerator "-reports:*/TestResults/*/coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
    - name: Publish
      run: dotnet nuget push **/*htmlc*.nupkg --no-symbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source "nuget.org"
