name: Nuget Deploy

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to use'
        required: true

jobs:
  nuget-deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ github.event.inputs.artifact_name }}
        # Destination path
        path: "/artifacts"
      
    - name: Publish
      run: dotnet nuget push /artifacts/*.nupkg --no-symbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source "nuget.org"
