name: Nuget Deploy

on: workflow_dispatch

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
    - name: List Artifacts
      id: list_artifacts
      uses: actions/artifact@v2
      with:
        name: my-artifact-name
          
    - name: Select Artifact
      uses: appleboy/gh-action-input@v1.0.6
      with:
        input_id: artifact
        message: 'Select an artifact:'
        type: select
        options: '${{ steps.list_artifacts.outputs.artifacts }}'
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ inputs.artifact }}
        # Destination path
        path: "/artifacts"
      
    - name: Publish
      run: dotnet nuget push /artifacts/*.nupkg --no-symbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source "nuget.org"
