name: Nuget Deploy

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'ID of the workflow run to use'
        required: true

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Get Artifact Name
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const runs = await github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-and-publish.yml',
            branch: 'main'
          });
          const run = runs.data.find(run => run.id == ${{ github.event.inputs.run_id }});
          const artifacts = await github.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run.id
          });
          core.setOutput('artifact_name', artifacts.data[0].name);
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ steps.get-artifact-name.outputs.artifact_name }}
        # Destination path
        path: "/artifacts"
      
    - name: Publish
      run: dotnet nuget push /artifacts/*.nupkg --no-symbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source "nuget.org"
